baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo-profile"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/FotoCV.jpg"
  name: "Claudia Villena Tagle"
  namecolor: ffc107
  profession: "Political scientist"
  github: "https://github.com/ClaudiaVillena27"
  linkedin: "https://www.linkedin.com/in/claudiavillenatagle/"
  facebook: "https://www.facebook.com/claudia.villena.52"

  # About
  disable_about: false
  descripe_l1_person: "Hello! My name is Claudia Villena. I graduated in Political Science and Government from the Pontificia Universidad Catolica del Peru (PUCP). I got an outstanding mention in my thesis investigation about corruption in public procurement. "
  descripe_l2_person: "I am currently working as an academic assistant in the PUCP, in the specialization of Political Science. Also, I am engaged in teaching activities as a Teachers's assistant in Political Economics at the same department. Prior to joining the PUCP, I worked as a project assistant in the Municipality of Miraflores, in the department of Urban Mobility and as Research Assistant in the Jurado Nacional de Elecciones (JNE), Peru. By the time, i have been working on developing my abilities in Data Science and quantitative methods of research. My goal is to develop my professional career in corruption and security field applying my analytical skills."
  

  skills:
    - name: SPSS
      percentage: 85
    - name: R Studio
      percentage: 85
    - name: Python
      percentage: 50
    - name: Google Data Studio
      percentage: 85

  # Experience
  disable_experience: false
  experience:
    - company: "Pontificia Universidad Católica del Perú"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Academic Assistant"
      startdate: Jul 2021
      enddate: present
      featuredpoints:
        - point: Atted the academic affairs of the Political Science Specialty, Social Science.
    - company: "Dirección Nacional de Educación y Formación Cívica Ciudadana (DNEF) del Jurado Nacional de Elecciones"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Research Assistant for the Visualization of data"
      startdate: Mar 2021
      enddate: Jun 2020
      featuredpoints:
        - point: Assistance in statistical analysis and visualization of data from research projects.
        - point: Assistance in the application of surveys and collection of quantitative and qualitative information.
        - point: Data analysis in R
    - company: "Subgerencia de Movilidad Urbana y Seguridad Vial. Municipalidad de Miraflores"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Project Assistant"
      startdate: Jan 2020
      enddate: Feb 2021
      featuredpoints:
        - point: Support in the elaboration of the Strategic Plan of the Municipality of Miraflores, departament of Urban Mobility.
        - point: Data analysis in R.
        - point: Development of visualization boards in Google DataStudio.

  # Education
  disable_education: false
  education:
    - degree: "Political Science"
      branch: "Social Science"
      university: "Pontificia Universidad Católica del Perú"
      startedyear: "2014"
      graduation: "2019"
    - degree: "Political Science. Student exchange semester"
      university: "Centro de Investigación y Docencia Económica. CIDE"
      startedyear: "2019"
    - degree: "Corruption"
      branch: "Business Strategies for A Better World Specialization"
      university: "University of Pensilvania"
      startedyear: "2022"
      

  # Projects
  disable_projects: false
  projects:
    - name: "Analysis of the experiences and degrees of tolerance with corruption in Peru (2019)"
      img: "/images/Foto1.png"
      githublink: "https://github.com/ClaudiaVillena27/Corruption_peru"
      featuredlink: "/"
      description: "This report seeks to analyze one of the most important inputs for the development of anti-corruption policies: the attitudes and experiences of Peruvians regarding corrupt behavior."
    - name: "The Construction Club: an approach to the study of corruption in public procurement in Peru (2002-2016)"
      img: "/images/Foto2.png"
      githublink: "https://tesis.pucp.edu.pe/repositorio/handle/20.500.12404/17882"
      featuredlink: "/"
      description: "This thesis seeks to develop a response to the phenomenon of corruption in the public procurement of infraestructural projects. It is argue that the characteristics of the weak governance of the infraestructure system in Peru and the corporate capture of the institutions in charge of public procurements, explain the high degree of corruption and collusion present between 2002-2016"
    - name: "In the shadow of legality: the causes of corruption in the contracting of public works (2011-2014)"
      img: "/images/Foto3.png"
      githublink: "https://tesis.pucp.edu.pe/repositorio/handle/20.500.12404/17164"
      featuredlink: "/"
      description: "It is argued that the corruption present in these two cases responds to a utilitarian rationality and strategic interaction present in the relationships between public and private actors (independent variable 1), and the existence of regulatory deficiencies in the contracting process (independent variable 2)."     
  # Achievements
  disable_achievements: false
  achievements:
    - title: Bachelor of Social Sciences. Mention in Political Science and Government
      description: PUCP
      img: "/images/bachillera.jpg"
      #url: https://example.com
    - title: Degree in Political Science and Government
      description: PUCP
      img: "/images/titulo.jpg"
      # url: https://example.com
    - title: Workshop on Statistical Tools for Socio-Analysis Politician
      description: CISEPA PUCP
      img: "/images/Estadistico.jpg"
    - title:  Training Course in Modernization of the Public Management
      description: Escuela de Gobierno y Políticas Públicas PUCP
      img: "/images/modernizacion.jpg"
    - title:  Introduction to Impact Assessment Workshop
      description: CISEPA PUCP
      img: "/images/Evalucion_impacto.jpg"
    - title:  Introduction to Social Research Workshop
      description: CISEPA PUCP
      img: "/images/Investigacion_social.jpg"
    - title:  Behavioral Design 
      description: Instituto Mexicano de Economía del Comportamiento
      img: "/images/economia_comportamiento.jpg"
    - title: Statistical analysis of data with r 
      description: PeruStat
      img: "/images/Analisis_estadistico_R.jpg"
    - title: data analysis, reporting and visualization with R markdown 
      description: Ciencia de Datos Ecuador
      img: "/images/r.jpg"
    - title: Data visualization georeferenced in R 
      description: SDC- Learning
      img: "/images/visualizacion_datos.jpg"

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or  want to star an investigation, I'll try my best to get back to you!
  email: "claudia.villena@pucp.edu.pe"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
